[package]
name = "egui_cpu"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euc = { git = "https://github.com/zesterer/euc" }
egui = { workspace = true, features = ["bytemuck"] }
image = { workspace = true, default-features = false }
derive_more = { version = "1", features = ["add", "mul"] }
vek = "0.17.1"
bytemuck = "1"

[dev-dependencies]
egui = { workspace = true, features = ["default_fonts"] }
egui_extras = { workspace = true, features = ["all_loaders"] }

[lints]
workspace = true
